### ISSUE TITLE
problem related to `import.meta.url`

### ISSUE THREAD

**Issue by sh-tiye** [nshen/test-npm-crate#1]
I was building npm package using wasm-pack as well, but turned out there was a problem. it told me that `import.meta.url` is `undefined` after vite bundled the code, in dev mode. I mean, I have built code inside `node_modules/` and Vite tries to rewrite the code a bit. In the end when it's loaded in a browser, the get `import.meta.url` wrong. However it works well after `vite build`.

Do you have a solution for such a case?

**Comment by nshen** [comment]
Hi, did you use [vite-plugin-wasm-pack](https://github.com/nshen/vite-plugin-wasm-pack) ? 
https://github.com/nshen/vite-plugin-wasm-pack#use-wasm-pack-package-installed-via-npm
I think `vite-plugin-wasm-pack` would replace `import.meta.url` to the correct url

**Comment by sh-tiye** [comment]
saw that but didn't try it. I prefer pre-build wasm and put that in `node_modules`. not everyone in the team would like to compile Rust by themselves.

**Comment by nshen** [comment]
even you put package in node_modules  or just install a package made by wasmpack via npm, you have to install  vite-plugin-wasm-pack ,and set the package name in the second param,  then `import.meta.url` will be correct, see
https://github.com/nshen/vite-plugin-wasm-pack#use-wasm-pack-package-installed-via-npm

**Comment by nshen** [comment]
```js
import { defineConfig } from 'vite';
import wasmPack from 'vite-plugin-wasm-pack';

export default defineConfig({
  build: {
    minify: false
  },
  // use test-npm-crate from https://www.npmjs.com/package/test-npm-crate
  // we have no local crate, so leave the first param an empty array
  plugins: [wasmPack([], ['test-npm-crate'])]
});
```

**Comment by sh-tiye** [comment]
> even you put package in node_modules or just install a package made by wasmpack via npm, you have to install vite-plugin-wasm-pack,

I didn't notice that.

I tried it locally but it does't work. I have a package with a scope, for example`@a/b/pkg/`, it's trying to read a wrong path: `@a/b/pkg/pkg.js`.

```
error when starting dev server:
Error: ENOENT: no such file or directory, open '/Users/$USER/gists/use-my-project/node_modules/@a/b/pkg/pkg.js'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at prepareBuild (/Users/$USER/gists/use-my-project/node_modules/vite-plugin-wasm-pack/dist/index.js:116:47)
    at Context.buildStart (/Users/$USER/gists/use-my-project/node_modules/vite-plugin-wasm-pack/dist/index.js:126:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 2)
    at async Object.buildStart (/Users/$USER/gists/use-my-project/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42319:13)
    at async Server.httpServer.listen (/Users/$USER/gists/use-my-project/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66919:21)
```

**Comment by nshen** [comment]
@shore-yong I think your scope is not allowed, you can only write `@somescope/somepackagename`

**Comment by sh-tiye** [comment]
> I tried it locally but it does't work. I have a package with a scope, for example `@a/b/pkg/`

my mistake, package name was `@our-org/pkg`. But the path has the second part duplicated. could you test with a scoped package on your side?

**Comment by nshen** [comment]
the second `pkg` is the default output dir of wasmpack,  

try this example replace with your package.  

https://github.com/nshen/vite-plugin-wasm-pack/tree/main/npm-crate-example

> > I tried it locally but it does't work. I have a package with a scope, for example `@a/b/pkg/`
> 
> my mistake, package name was `@our-org/pkg`. But the path has the second part duplicated. could you test with a scoped package on your side?

**Comment by sh-tiye** [comment]
I don't know, but I can fix my local problem by disabling behavior in vite:

```
  optimizeDeps: {
    exclude: ["@out-org/org-pkg"],
  },
```
